name: Lint PowerShell Scripts (native)

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run PSScriptAnalyzer
        shell: pwsh
        run: |
          Install-Module PSScriptAnalyzer -Scope CurrentUser -Force -ErrorAction Stop
          $ErrorActionPreference = 'Stop'
          Invoke-ScriptAnalyzer -Path ./AgentLogs.ps1 `
            -SettingsPath ./.github/pssa-ruleset.psd1 `
            -Recurse:$false -Severity Error,Warning -EnableExit
