name: Lint PowerShell Script

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Lint PowerShell script
        uses: microsoft/psscriptanalyzer-action@v1
        with:
          path: AgentLogs.ps1
